print("                                                               ")
print("       _____________________________                           ")
print("      |                             |                          ")
print("      |                             |                          ")
print("      |                             |                          ")
print("      |                             |                          ")
print("      |                             |                          ")
print("      |                           (   )                        ")
print("      |                          (     )                       ")
print("      |                           (   )                        ")
print("      |                             |                          ")
print("      |                             |                          ")
print("      |                        - - -|- - -                     ")
print("      |                             |                          ")
print("      |                            / \                         ")
print("      |                           /   \                        ")
print("      |\                         /     \                       ")
print("      | \                       /       \                      ")
print("      |  \                                                     ")
print("      |___\_____________________________________               ")
