def gallow_complete():
    print("                                                               ")
    print("       _____________________________                           ")
    print("      |                             |                          ")
    print("      |                             |                          ")
    print("      |                             |                          ")
    print("      |                             |                          ")
    print("      |                             |                          ")
    print("      |                           (   )                        ")
    print("      |                          (     )                       ")
    print("      |                           (   )                        ")
    print("      |                             |                          ")
    print("      |                             |                          ")
    print("      |                        - - -|- - -                     ")
    print("      |                             |                          ")
    print("      |                            / \                         ")
    print("      |                           /   \                        ")
    print("      |\                         /     \                       ")
    print("      | \                       /       \                      ")
    print("      |  \                                                     ")
    print("      |___\_____________________________________               ")

gallow_complete()
